[coyote3]
    aspc_collection = "asp_configs"
    users_collection = "users"
    asp_collection = "assay_specific_panels"
    schemas_collection = "schemas"
    roles_collection = "roles"
    permissions_collection = "permissions"
    insilico_genelist_collection = "insilico_genelists"
    civic_variants_collection = "civic_variants"
    civic_gene_collection = "civic_genes"
    oncokb_collection = "onkokb"
    oncokb_actionable_collection = "oncokb_actionable"
    oncokb_genes_collection = "oncokb_genes"
    brcaexchange_collection = "brcaexchange"
    iarc_tp53_collection = "iarc_tp53"
    cosmic_collection = "cosmic"
    vep_metadata_collection = "vep_metadata"
    hgnc_collection = "hgnc_genes"
    blacklist_collection = "blacklist"
    annotations_collection = "annotation"
    samples_collection = "samples"
    variants_collection = "variants"
    cnvs_collection = "cnvs"
    fusions_collection = "fusions"
    transloc_collection = "translocations"
    biomarkers_collection = "biomarkers"
    coverage_collection = "coverage"
    coverage2_collection = "panel_cov"
    groupcov_collection = "group_coverage"
    expression_collection = "hpaexpr"
    rna_expression_collection = "rna_expression"
    rna_qc_collection = "rna_qc"
    rna_classification_collection = "rna_classification"

[coyote_dev_3]
    aspc_collection = "asp_configs"
    users_collection = "users_beta2"
    asp_collection = "assay_specific_panels"
    schemas_collection = "schemas_beta2"
    roles_collection = "roles_beta2"
    permissions_collection = "permissions_beta2"
    insilico_genelist_collection = "insilico_genelist_beta2"
    groups_collection = "groups"
    canonical_collection = "refseq_canonical"
    annotations_collection = "annotation"
    blacklist_collection = "blacklist"
    samples_collection = "samples"
    variants_collection = "variants"
    cnvs_collection = "cnvs_wgs"
    fusions_collection = "fusions"
    transloc_collection = "transloc"
    biomarkers_collection = "biomarkers"
    expression_collection = "hpaexpr"
    coverage_collection = "coverage"
    coverage2_collection = "panel_cov"
    groupcov_collection = "group_coverage"
    civic_variants_collection = "civic_variants"
    civic_gene_collection = "civic_genes"
    oncokb_collection = "onkokb"
    oncokb_actionable_collection = "oncokb_actionable"
    oncokb_genes_collection = "oncokb_genes"
    brcaexchange_collection = "brcaexchange"
    iarc_tp53_collection = "iarc_tp53"
    cosmic_collection = "cosmic"
    vep_metadata_collection = "vep_metadata"
    hgnc_collection = "hgnc_genes"
    rna_expression_collection = "rna_expression"
    rna_qc_collection = "rna_qc"
    rna_classification_collection = "rna_classification"

[BAM_Service]
    bam_samples = "samples"
